=== ZhenshengLee/nv_driveworks/doc/3-drive-works-infra/5-配置文件/graphlet.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://nvidia.com/dw/graphlet.schema.json",
    "title": "DW Graphlet Descriptor",
    "description": "The descriptor of a DriveWorks graphlet. The keys in JSON should appear in the same order as the properties are documented in the schema.",
    "type": "object",
    "required": [
        "name",
        "inputPorts",
        "outputPorts",
        "parameters",
        "subcomponents",
        "connections"
    ],
    "additionalProperties": false,
    "properties": {
        "comment": {
            "description": "An optional description of the graphlet",
            "type": "string"
        },
        "name": {
            "description": "The unique name of the graphlet",
            "type": "string",
            "pattern": "^([a-z][a-z_]*::)*[a-zA-Z][a-zA-Z0-9_]*$"
        },
        "inputPorts": {
            "description": "The input ports. The order is user defined.",
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-Z][A-Z0-9_]*$": {
                    "description": "The key is the name of the input port (in MACRO_CASE) which must be unique within the collection of input ports in this graphlet. The value describes the port itself.",
                    "$ref": "#/$defs/port"
                }
            }
        },
        "outputPorts": {
            "description": "The output ports. The order is user defined.",
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-Z][A-Z0-9_]*$": {
                    "description": "The key is the name of the output port (in MACRO_CASE) which must be unique within the collection of output ports in this graphlet. The value describes the port itself.",
                    "$ref": "#/$defs/port"
                }
            }
        },
        "parameters": {
            "description": "The parameters. The order is user defined.",
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[a-z][a-zA-Z0-9_]*(\\.[a-z][a-zA-Z0-9_]*)?$": {
                    "description": "The key is the name of the parameter (in camelCase) which must be unique within the collection of parameters in this node. The value describes the parameter itself.",
                    "$ref": "#/$defs/parameter"
                }
            }
        },
        "subcomponents": {
            "description": "The subcomponents. The order should be alphabetical.",
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[a-z][a-zA-Z0-9]*$": {
                    "description": "The key is the name of the component instance (in camelCase() which must be unique within the collection of subcomponents in this node. The value describes the component instance itself.",
                    "$ref": "#/$defs/subcomponent"
                }
            }
        },
        "connections": {
            "description": "The connections. The order should be alphabetical based on the source and the connection parameter names.",
            "type": "array",
            "items": {
                "$ref": "#/$defs/connection"
            }
        }
    },
    "$defs": {
        "port": {
            "type": "object",
            "required": [
                "type"
            ],
            "additionalProperties": false,
            "properties": {
                "type": {
                    "description": "The C++ type name of the data",
                    "type": "string",
                    "minLength": 1
                },
                "array": {
                    "description": "The array size if this is an array of ports (default: a single non-array port)",
                    "type": "integer",
                    "minimum": 1
                },
                "bindingRequired": {
                    "description": "The flag if the port must be bound (default: false)",
                    "type": "boolean"
                },
                "comment": {
                    "description": "Any text describing the port (default: empty string)",
                    "type": "string"
                }
            }
        },
        "parameter": {
            "type": "object",
            "required": [
                "type"
            ],
            "additionalProperties": false,
            "properties": {
                "type": {
                    "description": "The C++ type name of the parameter",
                    "type": "string",
                    "minLength": 1
                },
                "array": {
                    "description": "The array size if this is an array of parameter values (default: a single-value parameter)",
                    "type": "integer",
                    "minimum": 1
                },
                "default": {
                    "description": "The default value (default: none)",
                    "type": [
                        "array",
                        "boolean",
                        "number",
                        "string"
                    ],
                    "items": {
                        "type": [
                            "boolean",
                            "number",
                            "string"
                        ]
                    }
                },
                "comment": {
                    "description": "Any text describing the parameter (default: empty string)",
                    "type": "string"
                }
            }
        },
        "subcomponent": {
            "type": "object",
            "required": [
                "componentType"
            ],
            "additionalProperties": false,
            "properties": {
                "componentType": {
                    "description": "The (relative) path of a component ending in .node.json / .graphlet.json. During the transition from GDL the second extension might also be prefixed with 'gdl-'.",
                    "type": "string",
                    "pattern": "^.+\\.(gdl-)?(node|graphlet)\\.json$"
                },
                "parameters": {
                    "description": "The parameters passed to the subcomponent. The order should be alphabetical.",
                    "type": "object",
                    "additionalProperties": false,
                    "patternProperties": {
                        "^([a-z][a-zA-Z0-9_]*(\\.[a-z][a-zA-Z0-9_]*)?|\\*)$": {
                            "description": "The key is the name of the parameter and must match a parameter declared in the descriptor of the referenced component. The parameter value can either be of primitive type or an homongeneous array of a primitive type. A string value as well as string values in an array are subject to substition. The string can be either the literal value or a placeholder referencing a parameter of this graphlet. The placeholder must have the form of '$paramName' or if the graphlet parameter is an array and only a single value should be passed '$paramName[N]' where N is an index within the array. To pass a literal '$' character it needs to be escaped using another '$' character. As a wildcard the key can be the string '*'. The corresponding value must be '$*'. If it is present all parameters of the graphlet are passed to the component if it has a parameter with a matching name. Additional explicit parameter can be present beside the wildcard and override the graphlet parameter values.",
                            "type": [
                                "array",
                                "boolean",
                                "number",
                                "string"
                            ],
                            "items": {
                                "type": [
                                    "boolean",
                                    "number",
                                    "string"
                                ]
                            }
                        }
                    }
                },
                "comment": {
                    "description": "Any text describing the subcomponent (default: empty string)",
                    "type": "string"
                }
            }
        },
        "connection": {
            "type": "object",
            "required": [
                "src",
                "dests"
            ],
            "additionalProperties": false,
            "properties": {
                "src": {
                    "description": "The name of the input port of the graphlet or an output port of a subcomponent (in the form 'subcomponentInstanceName.OUTPUT_PORT_NAME') optionally followed by a non-negative array index wrapped in brackets. If an empty string is provided, it means the connection is an INBOUND connection and the src comes outside of the DAG.",
                    "type": "string",
                    "pattern": "^$|^([a-z][a-zA-Z0-9]*\\.)?[A-Z][A-Z0-9_]*(\\[[0-9]+\\])?$"
                },
                "dests": {
                    "description": "The collection of ports receiving the data",
                    "type": "object",
                    "additionalProperties": false,
                    "patternProperties": {
                        "^$|^([a-z][a-zA-Z0-9]*\\.)?[A-Z][A-Z0-9_]*(\\[[0-9]+\\])?$": {
                            "description": "The key is the name of the output port of the graphlet or an input port of a subcomponent (in the form 'subcomponentInstanceName.INPUT_PORT_NAME') optionally followed by a non-negative array index wrapped in brackets. The value contains parameters specific to this destination port. The order of the parameters should be alphabetical. If an empty string is provided, it means the connection is an OUTBOUND connection and the dest goes outside of the DAG.",
                            "type": [
                                "object"
                            ],
                            "additionalProperties": false,
                            "patternProperties": {
                                "^[a-z][a-zA-Z0-9_-]*$": {
                                    "description": "The key is the name of the parameter and the value can either be any primitive type",
                                    "type": [
                                        "boolean",
                                        "number",
                                        "string"
                                    ]
                                }
                            }
                        }
                    }
                },
                "params": {
                    "description": "Parameters for multicast connections. The order should be alphabetical.",
                    "type": "object",
                    "additionalProperties": false,
                    "patternProperties": {
                        "^[a-z][a-zA-Z0-9_-]*$": {
                            "description": "The key is the name of the parameter and the value can any primitive type",
                            "type": [
                                "boolean",
                                "number",
                                "string"
                            ]
                        }
                    }
                }
            }
        }
    }
}

=== ZhenshengLee/nv_driveworks/driverorks-5.10/src/cgf/graphs/descriptions/graphlets/RadarSensor.graphlet.json
{
    "name": "RadarSensor",
    "inputPorts": {
        "VIRTUAL_SYNC_TIME": {
            "type": "dwTime_t"
        },
        "SENSOR_EXTRINSICS": {
            "type": "dwCalibratedExtrinsics"
        }
    },
    "outputPorts": {
        "SENSOR_PROPERTIES": {
            "type": "dwSensorNodeProperties"
        },
        "RADAR_PROCESSED_DATA": {
            "type": "dwRadarScan"
        },
        "RADAR_TIMESTAMP": {
            "type": "dwSensorTsAndID"
        },
        "NEXT_RADAR_TIMESTAMP": {
            "type": "dwTime_t"
        }
    },
    "parameters": {
        "sensorId": {
            "type": "size_t",
            "default": 7
        },
        "sensorAffinityMask": {
            "type": "int32_t",
            "default": 1
        },
        "sensorThreadPriority": {
            "type": "int32_t",
            "default": 99
        },
        "frameSkipMask": {
            "type": "dw::core::FixedString<32>",
            "default": ""
        }
    },
    "subcomponents": {
        "radarNode": {
            "componentType": "../../../../../src/dwframework/dwnodes/sensors/dwradarnode/dwRadarNode.node.json",
            "parameters": {
                "sensorId": "$sensorId",
                "frameSkipMask": "$frameSkipMask"
            }
        }
    },
    "connections": [
        {
            "src": "radarNode.SENSOR_PROPERTIES",
            "dests": {
                "SENSOR_PROPERTIES": {}
            }
        },
        {
            "src": "radarNode.PROCESSED_DATA",
            "dests": {
                "RADAR_PROCESSED_DATA": {}
            }
        },
        {
            "src": "radarNode.TIMESTAMP",
            "dests": {
                "RADAR_TIMESTAMP": {}
            }
        },
        {
            "src": "radarNode.NEXT_TIMESTAMP",
            "dests": {
                "NEXT_RADAR_TIMESTAMP": {}
            }
        },
        {
            "src": "VIRTUAL_SYNC_TIME",
            "dests": {
                "radarNode.VIRTUAL_SYNC_TIME": {}
            }
        },
        {
            "src": "SENSOR_EXTRINSICS",
            "dests": {
                "radarNode.SENSOR_EXTRINSICS": {}
            }
        }
    ]
}

=== ZhenshengLee/nv_driveworks/driveworks-5.8/src/cgf/graphs/descriptions/graphlets/RadarDopplerMotion.graphlet.json
{
    "$schema": "../../../../../../doc/3-drive-works-infra/7-基于json的cgf设计/graphlet.schema.json",
    "name": "RadarDopplerMotion",
    "inputPorts": {
        "RADAR_SCAN": {
            "type": "dwRadarScan",
            "array": 9
        }
    },
    "outputPorts": {
        "RADAR_DOPPLER_MOTION": {
            "type": "dwRadarDopplerMotion",
            "array": 9
        }
    },
    "parameters": {
        "radarDopplerMotionCudaStreamIndices": { "type": "int64_t", "array": 9, "default": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ] },
        "enabled": { "type": "bool", "array": 9, "default": [
            true,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            false
        ] }
    },
    "subcomponents": {
        "radarDopplerMotionNode0": {
            "componentType": "../../../../../src/dwframework/dwnodes/dwradardopplermotionnode/dwRadarDopplerMotionNode.node.json",
            "parameters": {
                "*": "$*",
                "index": 0
            }
        },
        "radarDopplerMotionNode1": {
            "componentType": "../../../../../src/dwframework/dwnodes/dwradardopplermotionnode/dwRadarDopplerMotionNode.node.json",
            "parameters": {
                "*": "$*",
                "index": 1
            }
        },
        "radarDopplerMotionNode2": {
            "componentType": "../../../../../src/dwframework/dwnodes/dwradardopplermotionnode/dwRadarDopplerMotionNode.node.json",
            "parameters": {
                "*": "$*",
                "index": 2
            }
        },
        "radarDopplerMotionNode3": {
            "componentType": "../../../../../src/dwframework/dwnodes/dwradardopplermotionnode/dwRadarDopplerMotionNode.node.json",
            "parameters": {
                "*": "$*",
                "index": 3
            }
        },
        "radarDopplerMotionNode4": {
            "componentType": "../../../../../src/dwframework/dwnodes/dwradardopplermotionnode/dwRadarDopplerMotionNode.node.json",
            "parameters": {
                "*": "$*",
                "index": 4
            }
        },
        "radarDopplerMotionNode5": {
            "componentType": "../../../../../src/dwframework/dwnodes/dwradardopplermotionnode/dwRadarDopplerMotionNode.node.json",
            "parameters": {
                "*": "$*",
                "index": 5
            }
        },
        "radarDopplerMotionNode6": {
            "componentType": "../../../../../src/dwframework/dwnodes/dwradardopplermotionnode/dwRadarDopplerMotionNode.node.json",
            "parameters": {
                "*": "$*",
                "index": 6
            }
        },
        "radarDopplerMotionNode7": {
            "componentType": "../../../../../src/dwframework/dwnodes/dwradardopplermotionnode/dwRadarDopplerMotionNode.node.json",
            "parameters": {
                "*": "$*",
                "index": 7
            }
        },
        "radarDopplerMotionNode8": {
            "componentType": "../../../../../src/dwframework/dwnodes/dwradardopplermotionnode/dwRadarDopplerMotionNode.node.json",
            "parameters": {
                "*": "$*",
                "index": 8
            }
        }
    },
    "connections": [
        {
            "src": "radarDopplerMotionNode0.RADAR_DOPPLER_MOTION",
            "dests": {"RADAR_DOPPLER_MOTION[0]": {}}
        },
        {
            "src": "radarDopplerMotionNode1.RADAR_DOPPLER_MOTION",
            "dests": {"RADAR_DOPPLER_MOTION[1]": {}}
        },
        {
            "src": "radarDopplerMotionNode2.RADAR_DOPPLER_MOTION",
            "dests": {"RADAR_DOPPLER_MOTION[2]": {}}
        },
        {
            "src": "radarDopplerMotionNode3.RADAR_DOPPLER_MOTION",
            "dests": {"RADAR_DOPPLER_MOTION[3]": {}}
        },
        {
            "src": "radarDopplerMotionNode4.RADAR_DOPPLER_MOTION",
            "dests": {"RADAR_DOPPLER_MOTION[4]": {}}
        },
        {
            "src": "radarDopplerMotionNode5.RADAR_DOPPLER_MOTION",
            "dests": {"RADAR_DOPPLER_MOTION[5]": {}}
        },
        {
            "src": "radarDopplerMotionNode6.RADAR_DOPPLER_MOTION",
            "dests": {"RADAR_DOPPLER_MOTION[6]": {}}
        },
        {
            "src": "radarDopplerMotionNode7.RADAR_DOPPLER_MOTION",
            "dests": {"RADAR_DOPPLER_MOTION[7]": {}}
        },
        {
            "src": "radarDopplerMotionNode8.RADAR_DOPPLER_MOTION",
            "dests": {"RADAR_DOPPLER_MOTION[8]": {}}
        },
        {
            "src": "RADAR_SCAN[0]",
            "dests": {"radarDopplerMotionNode0.RADAR_SCAN": {}}
        },
        {
            "src": "RADAR_SCAN[1]",
            "dests": {"radarDopplerMotionNode1.RADAR_SCAN": {}}
        },
        {
            "src": "RADAR_SCAN[2]",
            "dests": {"radarDopplerMotionNode2.RADAR_SCAN": {}}
        },
        {
            "src": "RADAR_SCAN[3]",
            "dests": {"radarDopplerMotionNode3.RADAR_SCAN": {}}
        },
        {
            "src": "RADAR_SCAN[4]",
            "dests": {"radarDopplerMotionNode4.RADAR_SCAN": {}}
        },
        {
            "src": "RADAR_SCAN[5]",
            "dests": {"radarDopplerMotionNode5.RADAR_SCAN": {}}
        },
        {
            "src": "RADAR_SCAN[6]",
            "dests": {"radarDopplerMotionNode6.RADAR_SCAN": {}}
        },
        {
            "src": "RADAR_SCAN[7]",
            "dests": {"radarDopplerMotionNode7.RADAR_SCAN": {}}
        },
        {
            "src": "RADAR_SCAN[8]",
            "dests": {"radarDopplerMotionNode8.RADAR_SCAN": {}}
        }
    ]
}

=== ZhenshengLee/nv_driveworks/driveworks-5.8/src/cgf/graphs/descriptions/graphlets/CameraSensor.graphlet.json
{
    "$schema": "../../../../../../doc/3-drive-works-infra/7-基于json的cgf设计/graphlet.schema.json",
    "name": "CameraSensor",
    "inputPorts": {
        "VIRTUAL_SYNC_TIME": {
            "type": "dwTime_t"
        },
        "SENSOR_EXTRINSICS": {
            "type": "dwCalibratedExtrinsics"
        }
    },
    "outputPorts": {
        "SENSOR_PROPERTIES": {
            "type": "dwSensorNodeProperties"
        },
        "INTRINSICS": {
            "type": "dwCameraIntrinsics"
        },
        "CUDA_PROCESSED": {
            "type": "dwImageHandle_t"
        },
        "CUDA_PROCESSED_RGBA": {
            "type": "dwImageHandle_t"
        },
        "CUDA_ISP_RGB_FP_16_HALF_RES": {
            "type": "dwImageHandle_t"
        },
        "CUDA_ISP_RGB_FP_16_HALF_RES_FOVEAL": {
            "type": "dwImageHandle_t"
        },
        "FOVEAL_SIGNAL": {
            "type": "bool"
        },
        "IMAGE_TIMESTAMP": {
            "type": "dwTime_t"
        },
        "NEXT_IMAGE_TIMESTAMP": {
            "type": "dwTime_t"
        }
    },
    "parameters": {
        "cameraIndex": { "type": "size_t", "default": 0 },
        "delayPostInit": { "type": "int32_t", "default": 0 },
        "fovealMode": { "type": "dwFovealMode", "default": "OFF" },
        "fovealROIX": { "type": "int32_t", "default": 480 },
        "fovealROIY": { "type": "int32_t", "default": 302 },
        "fovealROIWidth": { "type": "int32_t", "default": 960 },
        "fovealROIHeight": { "type": "int32_t", "default": 604 },
        "fovealScalesX": { "type": "float32_t", "default": 2 },
        "fovealScalesY": { "type": "float32_t", "default": 2 },
        "streamIndex": { "type": "size_t", "default": 0 },
        "useEEPROMIntrinsics": { "type": "bool", "default": false }
    },
    "subcomponents": {
        "cameraNode": {
            "componentType": "../../../../../src/dwframework/dwnodes/sensors/dwcameranode/dwCameraNode.node.json",
            "parameters": {
                "cameraIndex": "$cameraIndex",
                "streamIndex": "$streamIndex",
                "useEEPROMIntrinsics": "$useEEPROMIntrinsics"
            }
        },
        "ispNode": {
            "componentType": "../../../nodes/ISPNode.node.json",
            "parameters": {
                "*": "$*"
            }
        }
    },
    "connections": [
        {
            "src": "cameraNode.SENSOR_PROPERTIES",
            "dests": {"SENSOR_PROPERTIES": {}}
        },
        {
            "src": "cameraNode.INTRINSICS",
            "dests": {"INTRINSICS": {}}
        },
        {
            "src": "cameraNode.IMAGE_NATIVE_PROCESSED",
            "dests": {
                "ispNode.IMAGE": {},
                "CUDA_PROCESSED": {}
            },
            "params": {
                "singleton": true
            }
        },
        {
            "src": "cameraNode.IMAGE_PROCESSED_RGBA",
            "dests": {"CUDA_PROCESSED_RGBA": {}}
        },
        {
            "src": "cameraNode.IMAGE_TIMESTAMP",
            "dests": {"IMAGE_TIMESTAMP": {}}
        },
        {
            "src": "cameraNode.NEXT_IMAGE_TIMESTAMP",
            "dests": {"NEXT_IMAGE_TIMESTAMP": {}}
        },
        {
            "src": "ispNode.IMAGE",
            "dests": {"CUDA_ISP_RGB_FP_16_HALF_RES": {}}
        },
        {
            "src": "ispNode.IMAGE_FOVEAL",
            "dests": {"CUDA_ISP_RGB_FP_16_HALF_RES_FOVEAL": {}}
        },
        {
            "src": "ispNode.FOVEAL_SIGNAL",
            "dests": {"FOVEAL_SIGNAL": {}}
        },
        {
            "src": "VIRTUAL_SYNC_TIME",
            "dests": {"cameraNode.VIRTUAL_SYNC_TIME": {}}
        },
        {
            "src": "SENSOR_EXTRINSICS",
            "dests": {"cameraNode.SENSOR_EXTRINSICS": {}}
        }
    ]
}

=== ZhenshengLee/nv_driveworks/driveworks-5.8/src/cgf/graphs/descriptions/graphlets/EgomotionDemo.graphlet.json
{
    "$schema": "../../../../../../doc/3-drive-works-infra/7-基于json的cgf设计/graphlet.schema.json",
    "name": "EgomotionDemo",
    "inputPorts": {
        "IMU_FRAME": {
            "type": "dwIMUFrame"
        },
        "VEHICLE_STATE": {
            "type": "dwVehicleIOState"
        },
        "WHEEL_RADII": {
            "type": "dwCalibratedWheelRadii"
        },
        "VEHICLE_STATE_ODOMETRY_ONLY": {
            "type": "dwVehicleIOState"
        },
        "IMU_EXTRINSICS": {
            "type": "dwSensorNodeProperties"
        }
    },
    "outputPorts": {
        "EGOMOTION_STATE": {
            "type": "dwEgomotionStateHandle_t"
        },
        "ODOMETRY_ONLY_EGOMOTION_STATE": {
            "type": "dwEgomotionStateHandle_t"
        },
        "TRANSFORMATION_PAYLOAD": {
            "type": "dwTransformation3fPayload"
        },
        "EGOMOTION_RESULT_PAYLOAD": {
            "type": "dwEgomotionResultPayload"
        }
    },
    "parameters": {
        "enableSuspension": { "type": "bool", "default": true },
        "speedMeasurementType": { "type": "dwEgomotionSpeedMeasurementType", "default": "DW_EGOMOTION_REAR_WHEEL_SPEED" },
        "motionModel": { "type": "dwMotionModel", "default": "DW_EGOMOTION_IMU_ODOMETRY" },
        "estimateInitialOrientation": { "type": "bool", "default": false },
        "automaticUpdate": { "type": "bool", "default": true },
        "historySize": { "type": "uint32_t", "default": 1000 },
        "linearAccelerationFilterMode": { "type": "dwEgomotionLinearAccelerationFilterMode", "default": "DW_EGOMOTION_ACC_FILTER_SIMPLE" },
        "linearAccelerationFilterTimeConst": { "type": "float32_t", "default": 0.1 },
        "linearAccelerationFilterProcessNoiseStdevSpeed": { "type": "float32_t", "default": 0.1 },
        "linearAccelerationFilterProcessNoiseStdevAcceleration": { "type": "float32_t", "default": 1.0 },
        "linearAccelerationFilterMeasurementNoiseStdevSpeed": { "type": "float32_t", "default": 0.1 },
        "linearAccelerationFilterMeasurementNoiseStdevAcceleration": { "type": "float32_t", "default": 0.384 }
    },
    "subcomponents": {
        "relativeEgomotionNode": {
            "componentType": "../../../../../src/dwframework/dwnodes/egomotion/dwrelativeegomotionimunode/dwRelativeEgomotionIMUNode.node.json",
            "parameters": {
                "*": "$*"
            }
        },
        "odometryOnlyEgomotionNode": {
            "componentType": "../../../../../src/dwframework/dwnodes/egomotion/dwrelativeegomotionimunode/dwRelativeEgomotionIMUNode.node.json",
            "parameters": {
                "*": "$*",
                "motionModel": "DW_EGOMOTION_ODOMETRY",
                "historySize": 100
            }
        }
    },
    "connections": [
        {
            "src": "relativeEgomotionNode.EGOMOTION_STATE",
            "dests": {"EGOMOTION_STATE": {}}
        },
        {
            "src": "relativeEgomotionNode.TRANSFORMATION_PAYLOAD",
            "dests": {"TRANSFORMATION_PAYLOAD": {}}
        },
        {
            "src": "relativeEgomotionNode.EGOMOTION_RESULT_PAYLOAD",
            "dests": {"EGOMOTION_RESULT_PAYLOAD": {}}
        },
        {
            "src": "odometryOnlyEgomotionNode.EGOMOTION_STATE",
            "dests": {"ODOMETRY_ONLY_EGOMOTION_STATE": {}}
        },
        {
            "src": "IMU_FRAME",
            "dests": {"relativeEgomotionNode.IMU_FRAME": {}}
        },
        {
            "src": "VEHICLE_STATE",
            "dests": {"relativeEgomotionNode.VEHICLE_STATE": {}}
        },
        {
            "src": "WHEEL_RADII",
            "dests": {"relativeEgomotionNode.WHEEL_RADII": {}}
        },
        {
            "src": "VEHICLE_STATE_ODOMETRY_ONLY",
            "dests": {"odometryOnlyEgomotionNode.VEHICLE_STATE": {}}
        },
        {
            "src": "IMU_EXTRINSICS",
            "dests": {"relativeEgomotionNode.IMU_EXTRINSICS": {}}
        }
    ]
}

=== ZhenshengLee/nv_driveworks/driveworks-5.8/src/cgf/graphs/descriptions/graphlets/VehicleStateConsumer.graphlet.json
{
    "$schema": "../../../../../../doc/3-drive-works-infra/7-基于json的cgf设计/graphlet.schema.json",
    "name": "VehicleStateConsumer",
    "inputPorts": {
        "VIRTUAL_SYNC_TIME": {
            "type": "dwTime_t"
        }
    },
    "outputPorts": {
        "VEHICLE_IO_STATE": {
            "type": "dwVehicleIOState"
        },
        "NEXT_TIMESTAMP": {
            "type": "dwTime_t"
        }
    },
    "parameters": {
        "sensorAffinityMask": { "type": "int32_t", "default": 1 },
        "sensorThreadPriority": { "type": "int32_t", "default": 99 }
    },
    "subcomponents": {
        "vehicleStateNode": {
            "componentType": "../../../../../src/dwframework/dwnodes/sensors/dwvehiclestatenode/dwVehicleStateNode.node.json",
            "parameters": {
                "*": "$*",
                "legacyInternal": true,
                "legacyExternal": false,
                "external": false,
                "vioStateRcEnabled": false
            }
        }
    },
    "connections": [
        {
            "src": "vehicleStateNode.PROCESSED_DATA",
            "dests": {"VEHICLE_IO_STATE": {}}
        },
        {
            "src": "vehicleStateNode.NEXT_TIMESTAMP",
            "dests": {"NEXT_TIMESTAMP": {}}
        },
        {
            "src": "VIRTUAL_SYNC_TIME",
            "dests": {"vehicleStateNode.VIRTUAL_SYNC_TIME": {}}
        }
    ]
}
