=== ZhenshengLee/nv_driveworks/doc/3-drive-works-infra/7-基于json的cgf设计/5.10/node.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://nvidia.com/dw/node.schema.json",
    "title": "DW Node Descriptor",
    "description": "The descriptor of a DriveWorks node. The keys in JSON should appear in the same order as the properties are documented in the schema.",
    "type": "object",
    "required": [
        "name",
        "inputPorts",
        "outputPorts",
        "parameters",
        "passes"
    ],
    "additionalProperties": false,
    "properties": {
        "comment": {
            "description": "In a manually written JSON file this field can contain an arbitrary text. When the JSON file is generated, the tool should include its own name and optionally reference the authoritive source of information.",
            "type": "string"
        },
        "generated": {
            "description": "The flag if the JSON file was generated automatically - derived from an authoritive source - instead of being manually written and maintained.",
            "type": "boolean"
        },
        "library": {
            "description": "The basename of the shared library containing the node. Omitting this key indicates that the node has no implementation. The value 'static' indicates that the node is part of a statically linked library rather than a dynamically loaded shared library.",
            "type": "string",
            "pattern": "^(lib[a-z][a-zA-Z0-9_]*\\.so(\\.[0-9]+)*|static)$"
        },
        "name": {
            "description": "The fully qualified C++ type name of the node class",
            "type": "string",
            "pattern": "^([a-z][a-z_]*::)*[a-zA-Z][a-zA-Z0-9_]*$"
        },
        "inputPorts": {
            "description": "The input ports. The order is user defined and matches the order in the C++ code if applicable.",
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-Z][A-Z0-9_]*$": {
                    "description": "The key is the name of the input port (in MACRO_CASE) which must be unique within the collection of input ports in this node. The value describes the port itself.",
                    "$ref": "#/$defs/port"
                }
            }
        },
        "outputPorts": {
            "description": "The output ports. The order is user defined and matches the order in the C++ code if applicable.",
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-Z][A-Z0-9_]*$": {
                    "description": "The key is the name of the output port (in MACRO_CASE) which must be unique within the collection of output ports in this node. The value describes the port itself.",
                    "$ref": "#/$defs/port"
                }
            }
        },
        "parameters": {
            "description": "The parameters. The order is user defined and matches the order in the C++ code if applicable.",
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[a-z][a-zA-Z0-9_]*(\\.[a-z][a-zA-Z0-9_]*)?$": {
                    "description": "The key is the name of the parameter (in camelCase) which must be unique within the collection of parameters in this node. The value describes the parameter itself.",
                    "$ref": "#/$defs/parameter"
                }
            }
        },
        "passes": {
            "description": "The passes. The order is user defined and matches the order in the C++ code if applicable. In the default case where all passes are sequential this means the passes must follow topological order.",
            "type": "array",
            "items": {
                "$ref": "#/$defs/pass"
            },
            "uniqueItems": true
        }
    },
    "$defs": {
        "port": {
            "type": "object",
            "required": [
                "type"
            ],
            "additionalProperties": false,
            "properties": {
                "type": {
                    "description": "The C++ type name of the data",
                    "type": "string",
                    "minLength": 1
                },
                "array": {
                    "description": "The array size if this is an array of ports (default: a single non-array port)",
                    "type": "integer",
                    "minimum": 1
                },
                "bindingRequired": {
                    "description": "The flag if the port must be bound (default: false)",
                    "type": "boolean"
                },
                "comment": {
                    "description": "Any text describing the port. (default: empty string)",
                    "type": "string"
                }
            }
        },
        "parameter": {
            "type": "object",
            "required": [
                "type"
            ],
            "additionalProperties": false,
            "properties": {
                "type": {
                    "description": "The C++ type name of the parameter",
                    "type": "string",
                    "minLength": 1
                },
                "array": {
                    "description": "The array size if this is an array of parameter values (default: a single-value parameter)",
                    "type": "integer",
                    "minimum": 1
                },
                "default": {
                    "description": "The default value (default: none)",
                    "type": [
                        "array",
                        "boolean",
                        "number",
                        "string"
                    ],
                    "items": {
                        "type": [
                            "boolean",
                            "number",
                            "string"
                        ]
                    }
                }
            }
        },
        "pass": {
            "type": "object",
            "required": [
                "name",
                "processorTypes"
            ],
            "additionalProperties": false,
            "properties": {
                "name": {
                    "description": "The name of the pass which must be unique within the collection of passes in this node",
                    "type": "string",
                    "pattern": "^[A-Z][A-Z0-9_]*$"
                },
                "processorTypes": {
                    "description": "The processor types used by the pass (support is limited to a single processor type atm)",
                    "type": "array",
                    "minItems": 1,
                    "maxItems": 1,
                    "items": {
                        "enum": [
                            "CPU",
                            "GPU",
                            "DLA",
                            "PVA"
                        ]
                    }
                },
                "dependencies": {
                    "description": "The names of passes in this node dependent upon (default: the name of the previous pass in the array of passes in this node). The order should match the 'passes' array.",
                    "type": "array",
                    "items": {
                        "type": "string",
                        "pattern": "^[A-Z][A-Z0-9_]*$"
                    },
                    "uniqueItems": true
                }
            }
        }
    }
}

=== ZhenshengLee/nv_driveworks/driveworks-5.14/src/dwframework/dwnodes/egomotion/dwrelativeegomotionimunode/dwRelativeEgomotionIMUNode.node.json
{
    "comment": "Generated by the nodedescriptor tool based on data provided by the C++ API of the node class",
    "generated": true,
    "library": "libdwframework_dwnodes.so.5.14",
    "name": "dw::framework::dwRelativeEgomotionIMUNode",
    "inputPorts": {
        "IMU_FRAME": {
            "type": "dwIMUFrame"
        },
        "VEHICLE_IO_SAFETY_STATE": {
            "type": "dwVehicleIOSafetyState"
        },
        "VEHICLE_IO_NON_SAFETY_STATE": {
            "type": "dwVehicleIONonSafetyState"
        },
        "VEHICLE_IO_ACTUATION_FEEDBACK": {
            "type": "dwVehicleIOActuationFeedback"
        },
        "IMU_EXTRINSICS": {
            "type": "dwSensorNodeProperties"
        },
        "WHEEL_RADII": {
            "type": "dwCalibratedWheelRadii"
        }
    },
    "outputPorts": {
        "EGOMOTION_STATE": {
            "type": "dwEgomotionStateHandle_t"
        },
        "MODULE_HANDLE": {
            "type": "void*"
        },
        "EGOMOTION_POSE_PAYLOAD": {
            "type": "dwEgomotionPosePayload"
        },
        "IMU_INTRINSICS": {
            "type": "dwCalibratedIMUIntrinsics"
        }
    },
    "parameters": {
        "motionModel": {
            "type": "dwMotionModel"
        },
        "estimateInitialOrientation": {
            "type": "bool"
        },
        "automaticUpdate": {
            "type": "bool"
        },
        "enableSuspension": {
            "type": "bool"
        },
        "historySize": {
            "type": "uint32_t"
        },
        "speedMeasurementType": {
            "type": "dwEgomotionSpeedMeasurementType"
        },
        "linearAccelerationFilterMode": {
            "type": "dwEgomotionLinearAccelerationFilterMode"
        },
        "linearAccelerationFilterTimeConst": {
            "type": "float32_t"
        },
        "linearAccelerationFilterProcessNoiseStdevSpeed": {
            "type": "float32_t"
        },
        "linearAccelerationFilterProcessNoiseStdevAcceleration": {
            "type": "float32_t"
        },
        "linearAccelerationFilterMeasurementNoiseStdevSpeed": {
            "type": "float32_t"
        },
        "linearAccelerationFilterMeasurementNoiseStdevAcceleration": {
            "type": "float32_t"
        }
    },
    "passes": [
        {
            "name": "SETUP",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "ADD_IMU",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "ADD_VEHICLE_STATE",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "UPDATE_IMU_EXTRINSICS",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "UPDATE_WHEEL_RADII",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "SEND_STATE",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "TEARDOWN",
            "processorTypes": [
                "CPU"
            ]
        }
    ]
}

=== ZhenshengLee/nv_driveworks/driveworks-5.14/src/dwframework/dwnodes/sensors/dwlidarnode/dwLidarBatchNode.node.json
{
    "comment": "Generated by the nodedescriptor tool based on data provided by the C++ API of the node class",
    "generated": true,
    "library": "libdwframework_dwnodes.so.5.14",
    "name": "dw::framework::dwLidarBatchNode",
    "inputPorts": {
        "SENSOR_EXTRINSICS": {
            "type": "dwCalibratedExtrinsics"
        },
        "VIRTUAL_SYNC_TIME": {
            "type": "dwTime_t"
        }
    },
    "outputPorts": {
        "SENSOR_PROPERTIES": {
            "type": "dwSensorNodeProperties"
        },
        "PROCESSED_DATA": {
            "type": "dwLidarPacketsArray"
        },
        "RAW_DATA": {
            "type": "dwSensorNodeRawData"
        },
        "TIMESTAMP": {
            "type": "dwSensorTsAndID"
        },
        "NEXT_TIMESTAMP": {
            "type": "dwTime_t"
        }
    },
    "parameters": {
        "sensorId": {
            "type": "size_t"
        },
        "frameSkipMask": {
            "type": "dw::core::FixedString<32>"
        }
    },
    "passes": [
        {
            "name": "SETUP",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "RAW_OUTPUT",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "PROCESSED_OUTPUT",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "TEARDOWN",
            "processorTypes": [
                "CPU"
            ]
        }
    ]
}

=== ZhenshengLee/nv_driveworks/driverorks-5.10/src/dwframework/dwnodes/sensors/dwimunode/dwIMUNode.node.json
{
    "comment": "Generated by the nodedescriptor tool based on data provided by the C++ API of the node class",
    "generated": true,
    "library": "libdwframework_dwnodes.so.5.10",
    "name": "dw::framework::dwIMUNode",
    "inputPorts": {
        "SENSOR_EXTRINSICS": {
            "type": "dwCalibratedExtrinsics"
        },
        "VIRTUAL_SYNC_TIME": {
            "type": "dwTime_t",
            "bindingRequired": true
        },
        "FRAME": {
            "type": "dwIMUFrame",
            "bindingRequired": true
        }
    },
    "outputPorts": {
        "SENSOR_PROPERTIES": {
            "type": "dwSensorNodeProperties",
            "bindingRequired": true
        },
        "PROCESSED_DATA": {
            "type": "dwIMUFrame",
            "bindingRequired": true
        },
        "RAW_DATA": {
            "type": "dwSensorNodeRawData",
            "bindingRequired": true
        },
        "TIMESTAMP": {
            "type": "dwSensorTsAndID",
            "bindingRequired": true
        },
        "NEXT_TIMESTAMP": {
            "type": "dwTime_t",
            "bindingRequired": true
        }
    },
    "parameters": {
        "inputModeVal": {
            "type": "bool",
            "default": false
        },
        "frameSkipMask": {
            "type": "dw::core::FixedString<32>"
        }
    },
    "passes": [
        {
            "name": "SETUP",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "RAW_OUTPUT",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "PROCESSED_OUTPUT",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "TEARDOWN",
            "processorTypes": [
                "CPU"
            ]
        }
    ]
}

=== ZhenshengLee/nv_driveworks/driverorks-5.10/src/dwframework/dwnodes/selfcalibration/dwselfcalibrationnode/dwSelfCalibrationNode.node.json
{
    "comment": "Generated by the nodedescriptor tool based on data provided by the C++ API of the node class",
    "generated": true,
    "library": "libdwframework_dwnodes.so.5.10",
    "name": "dw::framework::dwSelfCalibrationNode",
    "inputPorts": {
        "EGOMOTION_STATE_ODO_IMU": {
            "type": "dwEgomotionStateHandle_t"
        },
        "VEHICLE_IO_STATE": {
            "type": "dwVehicleIOState"
        },
        "VEHICLE_IO_NON_SAFETY_STATE": {
            "type": "dwVehicleIONonSafetyState"
        },
        "CAMERA_FEATURE_DETECTION": {
            "type": "dwFeatureHistoryArray",
            "array": 13
        },
        "CAMERA_TIMESTAMP": {
            "type": "dwTime_t",
            "array": 13
        },
        "CAMERA_INTRINSICS": {
            "type": "dwCameraIntrinsics",
            "array": 13
        },
        "RADAR_DOPPLER_MOTION": {
            "type": "dwRadarDopplerMotion",
            "array": 9
        },
        "LIDAR_POINT_CLOUD": {
            "type": "dwPointCloud",
            "array": 8
        },
        "LIDAR_POSE": {
            "type": "dwLidarPose",
            "array": 8
        }
    },
    "outputPorts": {
        "CAMERA_EXTRINSICS": {
            "type": "dwCalibratedExtrinsics",
            "array": 13,
            "bindingRequired": true
        },
        "RADAR_EXTRINSICS": {
            "type": "dwCalibratedExtrinsics",
            "array": 9,
            "bindingRequired": true
        },
        "LIDAR_EXTRINSICS": {
            "type": "dwCalibratedExtrinsics",
            "array": 8,
            "bindingRequired": true
        },
        "WHEEL_RADII": {
            "type": "dwCalibratedWheelRadii",
            "bindingRequired": true
        },
        "FRONT_STEERING_OFFSET": {
            "type": "dwCalibratedSteeringProperties",
            "bindingRequired": true
        },
        "MODULE_HANDLE": {
            "type": "void*",
            "bindingRequired": true
        }
    },
    "parameters": {
        "enforceDependencies": {
            "type": "bool"
        },
        "calibrateVehicle": {
            "type": "bool"
        },
        "radarSensorWheelCalibration": {
            "type": "int32_t"
        },
        "cameraSensorIndices": {
            "type": "size_t",
            "array": 13
        },
        "cameraSensorStreamIndices": {
            "type": "size_t",
            "array": 13
        },
        "cameraEnabledMask": {
            "type": "bool",
            "array": 13
        },
        "cameraCalibrationMethod": {
            "type": "uint32_t",
            "array": 13
        },
        "cameraCalibrationSignals": {
            "type": "uint32_t",
            "array": 13
        },
        "radarSensorIndices": {
            "type": "size_t",
            "array": 9
        },
        "radarSensorStreamIndices": {
            "type": "size_t",
            "array": 9
        },
        "radarEnabledMask": {
            "type": "bool",
            "array": 9
        },
        "lidarSensorIndices": {
            "type": "size_t",
            "array": 8
        },
        "lidarSensorStreamIndices": {
            "type": "size_t",
            "array": 8
        },
        "lidarEnabledMask": {
            "type": "bool",
            "array": 8
        },
        "channelFifoSize": {
            "type": "uint32_t"
        }
    },
    "passes": [
        {
            "name": "SETUP",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "PROCESS_VIO",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "PROCESS_VEHICLE_IO_NON_SAFETY_STATE",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "PROCESS_CAMERA_GPU_ASYNC",
            "processorTypes": [
                "GPU"
            ]
        },
        {
            "name": "PROCESS_CAMERA_CPU_SYNC",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "PROCESS_RADAR",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "PROCESS_LIDAR_GPU_ASYNC",
            "processorTypes": [
                "GPU"
            ]
        },
        {
            "name": "PROCESS_LIDAR_CPU_SYNC",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "TEARDOWN",
            "processorTypes": [
                "CPU"
            ]
        }
    ]
}

=== ZhenshengLee/nv_driveworks/driveworks-5.8/src/dwframework/dwnodes/sensors/dwultrasonicnode/dwUltrasonicNode.node.json
{
    "$schema": "../../../../../../doc/3-drive-works-infra/7-基于json的cgf设计/node.schema.json",
    "comment": "Generated by the nodedescriptor tool based on data provided by the C++ API of the node class",
    "generated": true,
    "library": "libdwframework_dwnodes.so.5.8",
    "name": "dw::framework::dwUltrasonicNode",
    "inputPorts": {
        "SENSOR_EXTRINSICS": {
            "type": "dwCalibratedExtrinsics"
        },
        "VIRTUAL_SYNC_TIME": {
            "type": "dwTime_t",
            "bindingRequired": true
        },
        "VEHICLE_STATE": {
            "type": "dwVehicleIOState"
        }
    },
    "outputPorts": {
        "SENSOR_PROPERTIES": {
            "type": "dwSensorNodeProperties"
        },
        "PROCESSED_DATA": {
            "type": "dwUltrasonicGroup"
        },
        "RAW_DATA": {
            "type": "dwSensorNodeRawData"
        },
        "TIMESTAMP": {
            "type": "dwSensorTsAndID"
        },
        "NEXT_TIMESTAMP": {
            "type": "dwTime_t"
        },
        "MOUNTING_POSITIONS": {
            "type": "dwUltrasonicMountingPositions"
        }
    },
    "parameters": {},
    "passes": [
        {
            "name": "SETUP",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "RAW_OUTPUT",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "PROCESSED_OUTPUT",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "TEARDOWN",
            "processorTypes": [
                "CPU"
            ]
        }
    ]
}

=== ZhenshengLee/nv_driveworks/driveworks-5.8/src/dwframework/dwnodes/egomotion/dwrelativeegomotionimunode/dwRelativeEgomotionIMUNode.node.json
{
    "$schema": "../../../../../../doc/3-drive-works-infra/7-基于json的cgf设计/node.schema.json",
    "comment": "Generated by the nodedescriptor tool based on data provided by the C++ API of the node class",
    "generated": true,
    "library": "libdwframework_dwnodes.so.5.8",
    "name": "dw::framework::dwRelativeEgomotionIMUNode",
    "inputPorts": {
        "IMU_FRAME": {
            "type": "dwIMUFrame"
        },
        "VEHICLE_STATE": {
            "type": "dwVehicleIOState"
        },
        "VEHICLE_SAFETY_STATE": {
            "type": "dwVehicleIOSafetyState"
        },
        "VEHICLE_NON_SAFETY_STATE": {
            "type": "dwVehicleIONonSafetyState"
        },
        "VEHICLE_ACTUATION_FEEDBACK": {
            "type": "dwVehicleIOActuationFeedback"
        },
        "IMU_EXTRINSICS": {
            "type": "dwSensorNodeProperties"
        },
        "WHEEL_RADII": {
            "type": "dwCalibratedWheelRadii"
        }
    },
    "outputPorts": {
        "EGOMOTION_STATE": {
            "type": "dwEgomotionStateHandle_t"
        },
        "MODULE_HANDLE": {
            "type": "void*"
        },
        "TRANSFORMATION_PAYLOAD": {
            "type": "dwTransformation3fPayload"
        },
        "EGOMOTION_RESULT_PAYLOAD": {
            "type": "dwEgomotionResultPayload"
        },
        "IMU_INTRINSICS": {
            "type": "dwCalibratedIMUIntrinsics"
        }
    },
    "parameters": {
        "motionModel": {
            "type": "dwMotionModel"
        },
        "estimateInitialOrientation": {
            "type": "bool"
        },
        "automaticUpdate": {
            "type": "bool"
        },
        "enableSuspension": {
            "type": "bool"
        },
        "historySize": {
            "type": "uint32_t"
        },
        "speedMeasurementType": {
            "type": "dwEgomotionSpeedMeasurementType"
        },
        "linearAccelerationFilterMode": {
            "type": "dwEgomotionLinearAccelerationFilterMode"
        },
        "linearAccelerationFilterTimeConst": {
            "type": "float32_t"
        },
        "linearAccelerationFilterProcessNoiseStdevSpeed": {
            "type": "float32_t"
        },
        "linearAccelerationFilterProcessNoiseStdevAcceleration": {
            "type": "float32_t"
        },
        "linearAccelerationFilterMeasurementNoiseStdevSpeed": {
            "type": "float32_t"
        },
        "linearAccelerationFilterMeasurementNoiseStdevAcceleration": {
            "type": "float32_t"
        }
    },
    "passes": [
        {
            "name": "SETUP",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "ADD_IMU",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "ADD_ODOMETRY",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "UPDATE_IMU_EXTRINSICS",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "UPDATE_WHEEL_RADII",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "SEND_STATE",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "TEARDOWN",
            "processorTypes": [
                "CPU"
            ]
        }
    ]
}

=== ZhenshengLee/nv_driveworks/driverorks-5.10/src/dwframework/dwnodes/dwlidarpointcloudstitchernode/dwLidarPointCloudStitcherNode.node.json
{
    "comment": "Generated by the nodedescriptor tool based on data provided by the C++ API of the node class",
    "generated": true,
    "library": "libdwframework_dwnodes.so.5.10",
    "name": "dw::framework::dwLidarPointCloudStitcherNode",
    "inputPorts": {
        "LIDAR_PACKETS": {
            "type": "dwPointCloud",
            "array": 8
        },
        "LIDAR_EXTRINSICS": {
            "type": "dwSensorNodeProperties",
            "array": 8
        },
        "EGOMOTION_STATE": {
            "type": "dwEgomotionStateHandle_t"
        }
    },
    "outputPorts": {
        "POINT_CLOUD": {
            "type": "dwPointCloud",
            "bindingRequired": true
        },
        "TARGET_TIMESTAMP": {
            "type": "dwTime_t"
        }
    },
    "parameters": {
        "memoryType": {
            "type": "dwMemoryType"
        },
        "outputFormat": {
            "type": "dwPointCloudFormat"
        },
        "stream": {
            "type": "size_t"
        }
    },
    "passes": [
        {
            "name": "SETUP",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "PROCESS_GPU",
            "processorTypes": [
                "GPU"
            ]
        },
        {
            "name": "PROCESS_CPU",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "TEARDOWN",
            "processorTypes": [
                "CPU"
            ]
        }
    ]
}

=== ZhenshengLee/nv_driveworks/driverorks-5.10/src/dwframework/dwnodes/sensors/dwimunode/dwIMUChannelNode.node.json
{
    "comment": "Generated by the nodedescriptor tool based on data provided by the C++ API of the node class",
    "generated": true,
    "library": "libdwframework_dwnodes.so.5.10",
    "name": "dw::framework::dwIMUChannelNode",
    "inputPorts": {
        "SENSOR_EXTRINSICS": {
            "type": "dwCalibratedExtrinsics"
        },
        "VIRTUAL_SYNC_TIME": {
            "type": "dwTime_t",
            "bindingRequired": true
        },
        "INPUT_FRAME": {
            "type": "dwIMUFrame",
            "bindingRequired": true
        }
    },
    "outputPorts": {
        "SENSOR_PROPERTIES": {
            "type": "dwSensorNodeProperties",
            "bindingRequired": true
        },
        "PROCESSED_DATA": {
            "type": "dwIMUFrame",
            "bindingRequired": true
        },
        "TIMESTAMP": {
            "type": "dwSensorTsAndID",
            "bindingRequired": true
        },
        "NEXT_TIMESTAMP": {
            "type": "dwTime_t",
            "bindingRequired": true
        }
    },
    "parameters": {
        "frameSkipMask": {
            "type": "dw::core::FixedString<32>"
        }
    },
    "passes": [
        {
            "name": "SETUP",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "PROCESSED_OUTPUT",
            "processorTypes": [
                "CPU"
            ]
        },
        {
            "name": "TEARDOWN",
            "processorTypes": [
                "CPU"
            ]
        }
    ]
}
